routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\UserController;
use Whoops\Run;

Auth::routes(['verify' => true]);

// Contact Form Route
Route::post('Contact/Form', 'ContactController@SaveForm')->name('ContactForm');

// category routeo

Route::get('categories', 'HomeController@category')->name('categories');

Route::get('user/professional/{category_slug}', 'HomeController@professional')->name('users_professional');

//user route
Route::get('all/users', 'UserController@Userindex')->name('alluser');
// search
Route::get('search/users', 'UserController@userSearch')->name('usersearch');
Route::get('filter/search', 'UserController@filterSearch')->name('filter_search');
Route::get('filter/single/search', 'UserController@singleSearch')->name('filter_search_single');
Route::get('single/user/{id}', 'UserController@singleuser')->name('single-user')->middleware('admin_agent_employer');
// request route
Route::get('request/{user}', 'UserController@request')->name('request');

Route::post('requestform/{id}', 'UserController@storeRequest')->name('requestform');


//cv doenload
Route::get('/download/{id}', 'UserController@getDownload')->name('download');


Route::get('/', 'HomeController@index')->name('home');
Route::get('clear', 'HomeController@clearCache')->name('clear_cache');

Route::get('new-register', 'HomeController@newRegister')->name('new_register');
Route::get('job-seeker-register', 'UserController@registerJobSeeker')->name('register_job_seeker');
Route::post('job-seeker-register', 'UserController@registerJobSeekerPost');

Route::get('employer-register', 'UserController@registerEmployer')->name('register_employer');
Route::post('employer-register', 'UserController@registerEmployerPost');

Route::get('agent-register', 'UserController@registerAgent')->name('register_agent');
Route::post('agent-register', 'UserController@registerAgentPost');

Route::post('get-states-options', 'LocationController@getStatesOption')->name('get_state_option_by_country');

Route::get('apply_job', function () {
    return redirect(route('home'));
});
Route::post('apply_job', ['as' => 'apply_job', 'uses' => 'JobController@applyJob']);
Route::post('flag-job/{id}', ['as' => 'flag_job_post', 'uses' => 'JobController@flagJob']);
Route::post('share-by-email', ['as' => 'share_by_email', 'uses' => 'JobController@shareByEmail']);
Route::get('employer/{user_name}/jobs', 'JobController@jobsByEmployer')->name('jobs_by_employer');
Route::post('follow-unfollow', 'FollowerController@followUnfollow')->name('follow_unfollow');


Route::get('jobs/', 'JobController@jobsListing')->name('jobs_listing');

Route::get('p/{slug}', ['as' => 'single_page', 'uses' => 'PostController@showPage']);

Route::get('blog', 'PostController@blogIndex')->name('blog_index');
Route::get('blog/{slug}', 'PostController@view')->name('blog_post_single');

Route::get('pricing', 'HomeController@pricing')->name('pricing');

Route::get('contact-us', 'HomeController@contactUs')->name('contact_us');
Route::post('contact-us', 'HomeController@contactUsPost');

// new route
Route::get('about-us', 'HomeController@aboutUs')->name('about_us');
Route::get('how-it-work', 'HomeController@howItWork')->name('how_it_work');
Route::get('privacy-policy', 'HomeController@PrivacyPolicy')->name('privacy_policy');
Route::get('terms-conditions', 'HomeController@termsconditions')->name('terms_conditions');


//checkout
Route::get('checkout/{package_id}', 'PaymentController@checkout')->name('checkout')->middleware('auth');
Route::post('checkout/{package_id}', 'PaymentController@checkoutPost')->middleware('auth');

Route::get('payment/{transaction_id}', 'PaymentController@payment')->name('payment');
Route::post('payment/{transaction_id}', 'PaymentController@paymentPost');

Route::any('payment/{transaction_id}/success', 'PaymentController@paymentSuccess')->name('payment_success');
Route::any('payment-cancel', 'PaymentController@paymentCancelled')->name('payment_cancel');

//PayPal
Route::post('payment/{transaction_id}/paypal', 'PaymentController@paypalRedirect')->name('payment_paypal_pay');
Route::any('payment/paypal-notify/{transaction_id?}', 'PaymentController@paypalNotify')->name('paypal_notify');


Route::post('payment/{transaction_id}/stripe', 'PaymentController@paymentStripeReceive')->name('payment_stripe_receive');

Route::post('payment/{transaction_id}/bank-transfer', 'PaymentController@paymentBankTransferReceive')->name('bank_transfer_submit');


//Dashboard Route
Route::group(['prefix' => 'dashboard', ['middleware' => ['dashboard', 'verified']]], function () {
    Route::get('/', 'DashboardController@dashboard')->name('dashboard');

    Route::get('applied-jobs', 'DashboardController@dashboard')->name('applied_jobs');

    Route::get('request/table', 'UserController@requestTable')->name('Table');
    Route::get('reject/table/', 'UserController@rejectTable')->name('rejectUser');

    Route::get('request/aprove/{id}', 'UserController@aprove')->name('aprove');
    Route::get('request/reject/{id}', 'UserController@reject')->name('reject');
    Route::get('request/profile/{id}', 'UserController@requestUser')->name('requestUser');


    //show users 
    Route::get('allUser', 'UserController@allUser')->name('allUsers');
    Route::get('pending/users', 'UserController@pendingUsers')->name('pendingUsers');
    Route::get('blocked/users', 'UserController@blockedUsers')->name('blockedUsers');

    Route::get('viewUser/{id}', 'UserController@viewUser')->name('viewUser');
    Route::get('deleteUser/{id}', 'UserController@deleteUser')->name('deleteUser');
    Route::get('blockUser/{id}', 'UserController@blockUser')->name('blockUser');
    Route::get('unblockUser/{id}', 'UserController@unblockUser')->name('unblockUser');

    //company or employeer Route
    Route::get('allcompanies', 'UserController@allcompanies')->name('allcompanies');

    Route::get('viewCompany/{id}', 'UserController@viewCompany')->name('viewCompany');

    Route::get('blockCompany/{id}', 'UserController@blockCompany')->name('blockCompany');

    Route::get('deleteCompany/{id}', 'UserController@deleteCompany')->name('deleteCompany');

    Route::get('blocked/Companies', 'UserController@blockedCompanies')->name('blockedCompanies');

    Route::get('unblock/Company/{id}', 'UserController@unblockCompany')->name('unblockCompany');

    Route::get('pending/Companies', 'UserController@pendingCompanies')->name('pendingCompanies');


    // Request Against user
    Route::get('user/Request', 'UserController@userRequest')->name('userRequest');

    Route::get('reject-request', 'UserController@reject_request')->name('reject-request');




    Route::group(['middleware' => 'admin_agent_employer'], function () {

        Route::group(['prefix' => 'employer'], function () {

            Route::group(['prefix' => 'job'], function () {
                Route::get('new', 'JobController@newJob')->name('post_new_job');
                Route::post('new', 'JobController@newJobPost');
                Route::get('edit/{job_id}', 'JobController@edit')->name('edit_job');
                Route::post('edit/{job_id}', 'JobController@update');
                Route::get('posted', 'JobController@postedJobs')->name('posted_jobs');
            });

            Route::get('applicant', 'UserController@employerApplicant')->name('employer_applicant');
            Route::get('shortlisted', 'UserController@shortlistedApplicant')->name('shortlisted_applicant');
            Route::get('applicant/{application_id}/shortlist', 'UserController@makeShortList')->name('make_short_list');

            Route::get('profile', 'UserController@employerProfile')->name('employer_profile');
            Route::post('profile', 'UserController@employerProfilePost');
        });
        Route::group(['prefix' => 'jobs'], function () {
            Route::get('/', 'JobController@pendingJobs')->name('pending_jobs');
            Route::get('pending', 'JobController@approvedJobs')->name('approved_jobs');
            Route::get('blocked', 'JobController@blockedJobs')->name('blocked_jobs');
            Route::get('status/{id}/{status}', 'JobController@statusChange')->name('job_status_change');

            Route::get('applicants/{job_id}', 'JobController@jobApplicants')->name('job_applicants');
        });


        Route::get('flagged', 'JobController@flaggedMessage')->name('flagged_jobs');


        Route::group(['prefix' => 'cms'], function () {
            Route::get('/', 'PostController@index')->name('pages');
            Route::get('page/add', 'PostController@addPage')->name('add_page');
            Route::post('page/add', 'PostController@store');

            Route::get('page/edit/{id}', 'PostController@pageEdit')->name('page_edit');
            Route::post('page/edit/{id}', 'PostController@pageEditPost');

            Route::get('posts', 'PostController@indexPost')->name('posts');
            Route::get('post/add', 'PostController@addPost')->name('add_post');
            Route::post('post/add', 'PostController@storePost');

            Route::get('post/edit/{id}', 'PostController@postEdit')->name('post_edit');
            Route::post('post/edit/{id}', 'PostController@postUpdate');
        });
    });


    Route::group(['middleware' => 'only_admin_access'], function () {

        Route::group(['prefix' => 'categories'], function () {
            Route::get('/', ['as' => 'dashboard_categories', 'uses' => 'CategoriesController@index']);
            Route::post('/', ['uses' => 'CategoriesController@store']);

            Route::get('edit/{id}', ['as' => 'edit_categories', 'uses' => 'CategoriesController@edit']);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
    public $timestamps = false;

    public function jobs(){
        return $this->hasMany(Job::class);
    }

    public function active_jobs(){
        return $this->hasMany(Job::class)->whereStatus(1)->where('deadline', '>=', date('Y-m-d').' 00:00:00');
    }


    public function getCategoryNameAttribute($value){
        $last_cached = (int) get_option('category_count_cached');
        $refresh_time = $last_cached + (60*60);
        if ($refresh_time < time()){
            $this->job_count = $this->active_jobs->count();
            $this->save();

            update_option('category_count_cached', time());
        }


        return $value;
    }



    /*
        public function job_count(){
            return $this->hasMany(Job::class)->whereStatus(1)->count();
        }*/
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];

    public function getFeatureImageUriAttribute(){
        if ($this->feature_image){
            return asset('storage/uploads/images/blog/full/'.$this->feature_image);
        }
        return asset('assets/images/placeholder.png');
    }
    public function getFeatureImageThumbUriAttribute(){
        if ($this->feature_image){
            return asset('storage/uploads/images/blog/thumb/'.$this->feature_image);
        }
        return asset('assets/images/placeholder.png');
    }

    public function author(){
        return $this->belongsTo(User::class, 'user_id');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function jobs()
    {
        return $this->hasMany(Job::class)->orderBy('id', 'desc');
    }
    public function is_user()
    {
        return $this->user_type === 'user';
    }
    public function is_admin()
    {
        return $this->user_type === 'admin';
    }
    public function is_employer()
    {
        return $this->user_type === 'employer';
    }
    public function is_agent()
    {
        return $this->user_type === 'agent';
    }

    public function scopeEmployer($query)
    {
        return $query->whereUserType('employer');
    }
    public function scopeAgent($query)
    {
        return $query->whereUserType('agent');
    }
    public function isEmployerFollowed($employer_id = null)
    {
        if (!$employer_id || !Auth::check()) {
            return false;
        }

        $user = Auth::user();
        $isFollowed = UserFollowingEmployer::whereUserId($user->id)->whereEmployerId($employer_id)->first();

        if ($isFollowed) {
            return true;
        }
        return false;
    }

    public function getFollowersAttribute()
    {
        $followersCount = UserFollowingEmployer::whereEmployerId($this->id)->count();
        if ($followersCount) {
            return number_format($followersCount);
        }
        return 0;
    }

    public function getFollowableAttribute()
    {
        if (!Auth::check()) {
            return true;
        }

        $user = Auth::user();
        return $this->id !== $user->id;
    }

    public function getLogoUrlAttribute()
    {
        if ($this->logo) {
            return asset('storage/uploads/images/logos/' . $this->logo);
        }
        return asset('assets/images/company.png');
    }

    public function payments()
    {
        return $this->hasMany(Payment::class);
    }
    public function getPremiumJobsBalanceAttribute($value)
    {
        return $value;
    }

    public function checkJobBalace()
    {
        $totalPremiumJobsPaid = $this->payments()->success()->sum('premium_job');
        $totalPosted = $this->jobs()->whereIsPremium(1)->count();
        $balance = $totalPremiumJobsPaid - $totalPosted;

        $this->premium_jobs_balance = $balance;
        $this->save();
    }

    public function signed_up_datetime()
    {
        $created_date_time = $this->created_at->timezone(get_option('default_timezone'))->format(get_option('date_format_custom') . ' ' . get_option('time_format_custom'));
        return $created_date_time;
    }
    public function status_context()
    {
        $status = $this->active_status;

        $context = '';
        switch ($status) {
            case '0':
                $context = 'Pending';
                break;
            case '1':
                $context = 'Active';
                break;
            case '2':
                $context = 'Block';
                break;
        }
        return $context;
    }
}

resources/views/blog.blade.php
@extends('layouts.theme')

@section('content')

    <div class="blog-listing-page ">

        <div class="blog-listing-header ">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 offset-md-2 text-center">
                        <h1>{!! get_option('site_name') !!} @lang('app.blog')</h1>
                        <p>Get the latest updates from {!! get_option('site_name') !!}</p>

                        <div class="blog-search-wrap py-3">
                            <form method="get" class="form-inline justify-content-center">
                                <input type="text" name="q" value="{{request('q')}}" class="form-control mb-2" size="50" placeholder="Search blog">
                                <button type="submit" class="btn btn-danger mb-2">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">

                    <div class="blog-listing-content py-5">
                        @foreach($posts as $post)
                            <div class="blog-single-listing-wrap bg-white p-3 mb-4">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="blog-single-listing-img">
                                            <a href="{{route('blog_post_single', $post->slug)}}">
                                                <img src="{{$post->feature_image_thumb_uri}}" class="card-img" />
                                            </a>
                                        </div>
                                    </div>

                                    <div class="col-md-8">
                                        <div class="blog-single-listing-content">
                                            <a href="{{route('blog_post_single', $post->slug)}}">
                                                <h4>{{$post->title}}</h4>
                                            </a>

                                            <div class="blog-single-listing-footer text-muted mb-2">
                                                <span><i class="la la-user"></i> {{$post->author->name}} </span>
                                                <span><i class="la la-clock-o"></i> {{$post->created_at->diffForHumans()}} </span>
                                                <span><i class="la la-eye"></i> {{$post->views}} </span>
                                            </div>
                                            <p class="blog-card-text-preview mb-2">{!! limit_words($post->post_content, 20) !!}</p>
                                            <a href="{{route('blog_post_single', $post->slug)}}"> <i class="la la-book"></i> Read More</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach

                        {!! $posts->appends(['q' => request('q')])->links() !!}

                    </div>

                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/jobs-by-employer.blade.php
@extends('layouts.theme')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <div class="employer-job-listing mt-4">


                    @if($employer->jobs->count())


                        @foreach($employer->jobs as $job)
                            <div class="employer-job-listing-single box-shadow bg-white mb-4 p-3">

                                <h5><a href="{{route('job_view', $job->job_slug)}}">{!! $job->job_title !!}</a> </h5>

                                <p class="text-muted">
                                    <i class="la la-briefcase"></i> @lang('app.'.$job->job_type)

                                    <i class="la la-map-marker"></i>
                                    @if($job->city_name)
                                        {!! $job->city_name !!},
                                    @endif
                                    @if($job->state_name)
                                        {!! $job->state_name !!},
                                    @endif
                                    @if($job->country_name)
                                        {!! $job->country_name !!}
                                    @endif

                                    <i class="la la-clock-o"></i> @lang('app.posted') {{$job->created_at->diffForHumans()}}

                                    <i class="la la-calendar-times-o"></i> @lang('app.deadline') : {{$job->deadline->format(get_option('date_format'))}} <span class="text-small text-muted">{{$job->deadline->diffForHumans()}}</span>
                                </p>




                            </div>

                        @endforeach


                    @endif


                </div>

            </div>
        </div>
    </div>

@endsection

resources/views/jobs.blade.php
@extends('layouts.theme')

@section('content')


    <div class="blog-listing-header ">
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2 text-center">
                    <h1>@lang('app.search_jobs')</h1>
                    <h5>Filter from the left sidebar to find your desired job</h5>
                </div>
            </div>
        </div>
    </div>



    <div class="container">
        <div class="row">

            <div class="col-md-4">


                <div class="jobs-filter-form-wrap bg-white p-4 mt-4 mb-4">

                    <h4 class="mb-4">@lang('app.filter_jobs')</h4>

                    <form action="" method="get">

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.keywords')</p>
                            <input type="text" name="q" value="{{request('q')}}" class="form-control" style="min-width: 300px;" placeholder="@lang('app.job_title_placeholder')">
                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.gender')</p>

                            <select class="form-control" name="gender" id="gender">
                                <option value="">@lang('app.select_gender')</option>
                                <option value="any" {{ request('gender') == 'any' ? 'selected':'' }}>@lang('app.any')</option>
                                <option value="male" {{ request('gender') == 'male' ? 'selected':'' }}>@lang('app.male')</option>
                                <option value="female" {{ request('gender') == 'female' ? 'selected':'' }}>@lang('app.female')</option>
                                <option value="transgender" {{ request('gender') == 'transgender' ? 'selected':'' }}>@lang('app.transgender')</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.exp_level')</p>

                            <select class="form-control" name="exp_level" id="exp_level">
                                <option value="" >@lang('app.select_exp_level')</option>
                                <option value="mid" {{ request('exp_level') == 'mid' ? 'selected':'' }}>@lang('app.mid')</option>
                                <option value="entry" {{ request('exp_level') == 'entry' ? 'selected':'' }}>@lang('app.entry')</option>
                                <option value="senior" {{ request('exp_level') == 'senior' ? 'selected':'' }}>@lang('app.senior')</option>
                            </select>
                        </div>


                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.job_type')</p>

                            <select class="form-control" name="job_type" id="job_type">
                                <option value="">@lang('app.select_job_type')</option>
                                <option value="full_time" {{ request('job_type') == 'full_time' ? 'selected':'' }}>@lang('app.full_time')</option>
                                <option value="internship" {{ request('job_type') == 'internship' ? 'selected':'' }}>@lang('app.internship')</option>
                                <option value="part_time" {{ request('job_type') == 'part_time' ? 'selected':'' }}>@lang('app.part_time')</option>
                                <option value="contract" {{ request('job_type') == 'contract' ? 'selected':'' }}>@lang('app.contract')</option>
                                <option value="temporary" {{ request('job_type') == 'temporary' ? 'selected':'' }}>@lang('app.temporary')</option>
                                <option value="commission" {{ request('job_type') == 'commission' ? 'selected':'' }}>@lang('app.commission')</option>
                                <option value="internship" {{ request('job_type') == 'internship' ? 'selected':'' }}>@lang('app.internship')</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.category')</p>

                            <select class="form-control" name="category" id="category">
                                <option value="">@lang('app.select_category')</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}" {{selected($category->id, request('category'))}} >{{$category->category_name}}</option>
                                @endforeach
                            </select>

                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.country')</p>

                            <select name="country" class="form-control {{e_form_invalid_class('country', $errors)}} country_to_state">
                                <option value="">@lang('app.select_a_country')</option>
                                @foreach($countries as $country)
                                    <option value="{!! $country->id !!}" @if(request('country') && $country->id == request('country')) selected="selected" @endif  >{!! $country->country_name !!}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.state')</p>

                            <select name="state" class="form-control {{e_form_invalid_class('state', $errors)}} state_options">
                                <option value="">Select a state</option>

                                @if($old_country)
                                    @foreach($old_country->states as $state)
                                        <option value="{{$state->id}}" @if(request('state') && $state->id == request('state')) selected="selected" @endif >{!! $state->state_name !!}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.location')</p>
                            <input type="text" name="location" value="{{request('location')}}" class="form-control" style="min-width: 300px;"  placeholder="@lang('app.job_location_placeholder')">
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-danger"><i class="la la-search"></i> @lang('app.filter_jobs')</button>
                            <a href="{{route('jobs_listing')}}" class="btn btn-info text-white"><i class="la la-eraser"></i> @lang('app.clear_filter')</a>
                        </div>
                    </form>

                </div>

            </div>

            <div class="col-md-8">

                <div class="employer-job-listing mt-4">

                    @if($jobs->count())

                        <div class="job-search-stats bg-white mb-3 p-4">
                            {!! sprintf(__('app.job_search_stats'), '<strong>', $jobs->total(), '</strong>') !!}
                        </div>

                        @foreach($jobs as $job)
                            <div class="employer-job-listing-single {{$job->is_premium? ' premium-job ' : '' }} box-shadow bg-white mb-3 p-3">

                                @if($job->is_premium)
                                    <div class="job-listing-company-logo">
                                        <a href="{{route('job_view', $job->job_slug)}}">
                                            <img src="{{$job->employer->logo_url}}" class="img-fluid" />
                                        </a>
                                    </div>
                                @endif

                                <div class="listing-job-info">

                                    <h5><a href="{{route('job_view', $job->job_slug)}}">{!! $job->job_title !!}</a> </h5>
                                    <p class="text-muted mb-1 mt-1">

                                        <i class="la la-clock-o"></i> @lang('app.posted') {{$job->created_at->diffForHumans()}}

                                        <i class="la la-calendar-times-o"></i> @lang('app.deadline') : {{$job->deadline->format(get_option('date_format'))}} <span class="text-small text-muted">{{$job->deadline->diffForHumans()}}</span>
                                    </p>

                                    @if($job->is_premium)
                                        <p class="text-muted mb-1 mt-1">
                                            <i class="la la-money"></i> {!! get_amount($job->salary, $job->salary_currency) !!} @if($job->salary_upto) - {!! get_amount($job->salary_upto, $job->salary_currency) !!} @endif / @lang('app.'.$job->salary_cycle),
                                            <i class="la la-th-list"></i> @lang('app.exp_level') : @lang('app.'.$job->exp_level)
                                        </p>




                                    @endif


                                    <p class="text-muted">
                                        <i class="la la-building-o"></i> {{$job->employer->company}}
                                        <i class="la la-briefcase"></i> @lang('app.'.$job->job_type)
                                        <i class="la la-map-marker"></i>
                                        @if($job->city_name)
                                            {!! $job->city_name !!},
                                        @endif
                                        @if($job->state_name)
                                            {!! $job->state_name !!},
                                        @endif
                                        @if($job->country_name)
                                            {!! $job->country_name !!}
                                        @endif
                                    </p>

                                </div>


                            </div>

                        @endforeach



                    @else


                        <div class="no-search-results-wrap text-center">

                            <p class="p-4">
                                <img src="{{asset('assets/images/no-search.png')}}" />
                            </p>

                            <h3>Whoops, no mathces</h3>
                            <h5 class="text-muted">We couldn't find any search results. </h5>
                            <h5 class="text-muted">Give it another try</h5>

                        </div>

                    @endif

                    {!! $jobs->links() !!}

                </div>

            </div>
        </div>
    </div>

@endsection