codecanyon-23015013-jobfair-premium-laravel-php-job-board-script/jobfair/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('clear', 'HomeController@clearCache')->name('clear_cache');

Route::get('new-register', 'HomeController@newRegister')->name('new_register');
Route::get('job-seeker-register', 'UserController@registerJobSeeker')->name('register_job_seeker');
Route::post('job-seeker-register', 'UserController@registerJobSeekerPost');

Route::get('employer-register', 'UserController@registerEmployer')->name('register_employer');
Route::post('employer-register', 'UserController@registerEmployerPost');

Route::get('agent-register', 'UserController@registerAgent')->name('register_agent');
Route::post('agent-register', 'UserController@registerAgentPost');

Route::post('get-states-options', 'LocationController@getStatesOption')->name('get_state_option_by_country');

Route::get('apply_job', function (){
    return redirect(route('home'));
});
Route::post('apply_job', ['as' => 'apply_job', 'uses'=>'JobController@applyJob']);
Route::post('flag-job/{id}', ['as' => 'flag_job_post', 'uses'=>'JobController@flagJob']);
Route::post('share-by-email', ['as' => 'share_by_email', 'uses'=>'JobController@shareByEmail']);
Route::get('employer/{user_name}/jobs', 'JobController@jobsByEmployer')->name('jobs_by_employer');
Route::post('follow-unfollow', 'FollowerController@followUnfollow')->name('follow_unfollow');


Route::get('jobs/', 'JobController@jobsListing')->name('jobs_listing');

Route::get('p/{slug}', ['as' => 'single_page', 'uses' => 'PostController@showPage']);

Route::get('blog', 'PostController@blogIndex')->name('blog_index');
Route::get('blog/{slug}', 'PostController@view')->name('blog_post_single');

Route::get('pricing', 'HomeController@pricing')->name('pricing');

Route::get('contact-us', 'HomeController@contactUs')->name('contact_us');
Route::post('contact-us', 'HomeController@contactUsPost');


//checkout
Route::get('checkout/{package_id}', 'PaymentController@checkout')->name('checkout')->middleware('auth');
Route::post('checkout/{package_id}', 'PaymentController@checkoutPost')->middleware('auth');

Route::get('payment/{transaction_id}', 'PaymentController@payment')->name('payment');
Route::post('payment/{transaction_id}', 'PaymentController@paymentPost');

Route::any('payment/{transaction_id}/success', 'PaymentController@paymentSuccess')->name('payment_success');
Route::any('payment-cancel', 'PaymentController@paymentCancelled')->name('payment_cancel');

//PayPal
Route::post('payment/{transaction_id}/paypal', 'PaymentController@paypalRedirect')->name('payment_paypal_pay');
Route::any('payment/paypal-notify/{transaction_id?}', 'PaymentController@paypalNotify')->name('paypal_notify');


Route::post('payment/{transaction_id}/stripe', 'PaymentController@paymentStripeReceive')->name('payment_stripe_receive');

Route::post('payment/{transaction_id}/bank-transfer', 'PaymentController@paymentBankTransferReceive')->name('bank_transfer_submit');


//Dashboard Route
Route::group(['prefix'=>'dashboard', 'middleware' => 'dashboard'], function(){
    Route::get('/', 'DashboardController@dashboard')->name('dashboard');

    Route::get('applied-jobs', 'DashboardController@dashboard')->name('applied_jobs');


    Route::group(['middleware'=>'admin_agent_employer'], function(){

        Route::group(['prefix'=>'employer'], function(){

            Route::group(['prefix'=>'job'], function(){
                Route::get('new', 'JobController@newJob')->name('post_new_job');
                Route::post('new', 'JobController@newJobPost');
                Route::get('edit/{job_id}', 'JobController@edit')->name('edit_job');
                Route::post('edit/{job_id}', 'JobController@update');
                Route::get('posted', 'JobController@postedJobs')->name('posted_jobs');
            });

            Route::get('applicant', 'UserController@employerApplicant')->name('employer_applicant');
            Route::get('shortlisted', 'UserController@shortlistedApplicant')->name('shortlisted_applicant');
            Route::get('applicant/{application_id}/shortlist', 'UserController@makeShortList')->name('make_short_list');

            Route::get('profile', 'UserController@employerProfile')->name('employer_profile');
            Route::post('profile', 'UserController@employerProfilePost');

        });
        Route::group(['prefix'=>'jobs'], function(){
            Route::get('/', 'JobController@pendingJobs')->name('pending_jobs');
            Route::get('pending', 'JobController@approvedJobs')->name('approved_jobs');
            Route::get('blocked', 'JobController@blockedJobs')->name('blocked_jobs');
            Route::get('status/{id}/{status}', 'JobController@statusChange')->name('job_status_change');

            Route::get('applicants/{job_id}', 'JobController@jobApplicants')->name('job_applicants');
        });


        Route::get('flagged', 'JobController@flaggedMessage')->name('flagged_jobs');


        Route::group(['prefix'=>'cms'], function(){
            Route::get('/', 'PostController@index')->name('pages');
            Route::get('page/add', 'PostController@addPage')->name('add_page');
            Route::post('page/add', 'PostController@store');

            Route::get('page/edit/{id}', 'PostController@pageEdit')->name('page_edit');
            Route::post('page/edit/{id}', 'PostController@pageEditPost');

            Route::get('posts', 'PostController@indexPost')->name('posts');
            Route::get('post/add', 'PostController@addPost')->name('add_post');
            Route::post('post/add', 'PostController@storePost');

            Route::get('post/edit/{id}', 'PostController@postEdit')->name('post_edit');
            Route::post('post/edit/{id}', 'PostController@postUpdate');

        });

    });


    Route::group(['middleware'=>'only_admin_access'], function(){

        Route::group(['prefix'=>'categories'], function(){
            Route::get('/', ['as'=>'dashboard_categories', 'uses' => 'CategoriesController@index']);
            Route::post('/', ['uses' => 'CategoriesController@store']);

            Route::get('edit/{id}', ['as'=>'edit_categories', 'uses' => 'CategoriesController@edit']);
            Route::post('edit/{id}', ['uses' => 'CategoriesController@update']);

            Route::post('delete-categories', ['as'=>'delete_categories', 'uses' => 'CategoriesController@destroy']);
        });

        //Settings
        Route::group(['prefix'=>'settings'], function(){
            Route::get('/', 'SettingsController@GeneralSettings')->name('general_settings');

            Route::get('theme-settings', 'SettingsController@ThemeSettings')->name('theme_settings');
            Route::get('gateways', 'SettingsController@GatewaySettings')->name('gateways_settings');
            Route::get('pricing', 'SettingsController@PricingSettings')->name('pricing_settings');
            Route::post('pricing', 'SettingsController@PricingSave');

            //Save settings / options
            Route::post('save-settings', ['as'=>'save_settings', 'uses' => 'SettingsController@update']);
        });
    });


    Route::group(['prefix'=>'payments'], function() {
        Route::get('/', 'PaymentController@index')->name('payments');

        Route::get('view/{id}', ['as'=>'payment_view', 'uses' => 'PaymentController@view']);
        Route::get('status-change/{id}/{status}', ['as'=>'status_change', 'uses' => 'PaymentController@markSuccess']);
    });

    Route::group(['prefix'=>'u'], function(){
        Route::get('applied-jobs', 'UserController@appliedJobs')->name('applied_jobs');
        Route::get('profile', 'UserController@profile')->name('profile');
        Route::get('profile/edit', 'UserController@profileEdit')->name('profile_edit');
        Route::post('profile/edit', 'UserController@profileEditPost');

        Route::group(['prefix'=>'users'], function(){
            Route::get('/', 'UserController@index')->name('users');
            Route::get('view/{slug}', ['as'=>'users_view', 'uses' => 'UserController@show']);
            Route::get('user_status/{id}/{status}', 'UserController@statusChange')->name('user_status');

            //Edit
            Route::get('edit/{id}', ['as'=>'users_edit', 'uses' => 'UserController@profileEdit']);
            Route::post('edit/{id}', ['uses' => 'UserController@profileEditPost']);
            Route::get('profile/change-avatar/{id}', ['as'=>'change_avatar', 'uses' => 'UserController@changeAvatar']);
        });

        /**
         * Change Password route
         */
        Route::group(['prefix' => 'account'], function() {
            Route::get('change-password', ['as' => 'change_password', 'uses' => 'UserController@changePassword']);
            Route::post('change-password', 'UserController@changePasswordPost');
        });

    });

    Route::group(['prefix' => 'account'], function() {
        Route::get('change-password', 'UserController@changePassword')->name('change_password');
        Route::post('change-password', 'UserController@changePasswordPost');
    });

});


//Single Sigment View
Route::get('{slug}', 'JobController@view')->name('job_view');

codecanyon-23015013-jobfair-premium-laravel-php-job-board-script/jobfair/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
    public $timestamps = false;

    public function jobs(){
        return $this->hasMany(Job::class);
    }

    public function active_jobs(){
        return $this->hasMany(Job::class)->whereStatus(1)->where('deadline', '>=', date('Y-m-d').' 00:00:00');
    }


    public function getCategoryNameAttribute($value){
        $last_cached = (int) get_option('category_count_cached');
        $refresh_time = $last_cached + (60*60);
        if ($refresh_time < time()){
            $this->job_count = $this->active_jobs->count();
            $this->save();

            update_option('category_count_cached', time());
        }


        return $value;
    }



    /*
        public function job_count(){
            return $this->hasMany(Job::class)->whereStatus(1)->count();
        }*/
}

codecanyon-23015013-jobfair-premium-laravel-php-job-board-script/jobfair/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];

    public function getFeatureImageUriAttribute(){
        if ($this->feature_image){
            return asset('storage/uploads/images/blog/full/'.$this->feature_image);
        }
        return asset('assets/images/placeholder.png');
    }
    public function getFeatureImageThumbUriAttribute(){
        if ($this->feature_image){
            return asset('storage/uploads/images/blog/thumb/'.$this->feature_image);
        }
        return asset('assets/images/placeholder.png');
    }

    public function author(){
        return $this->belongsTo(User::class, 'user_id');
    }

}

codecanyon-23015013-jobfair-premium-laravel-php-job-board-script/jobfair/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function jobs(){
        return $this->hasMany(Job::class)->orderBy('id', 'desc');
    }
    public function is_user(){
        return $this->user_type === 'user';
    }
    public function is_admin(){
        return $this->user_type === 'admin';
    }
    public function is_employer(){
        return $this->user_type === 'employer';
    }
    public function is_agent(){
        return $this->user_type === 'agent';
    }

    public function scopeEmployer($query){
        return $query->whereUserType('employer');
    }
    public function scopeAgent($query){
        return $query->whereUserType('agent');
    }
    public function isEmployerFollowed($employer_id = null){
        if ( ! $employer_id || ! Auth::check()){
            return false;
        }

        $user = Auth::user();
        $isFollowed = UserFollowingEmployer::whereUserId($user->id)->whereEmployerId($employer_id)->first();

        if($isFollowed){
            return true;
        }
        return false;
    }

    public function getFollowersAttribute(){
        $followersCount = UserFollowingEmployer::whereEmployerId($this->id)->count();
        if ($followersCount){
            return number_format($followersCount);
        }
        return 0;
    }

    public function getFollowableAttribute(){
        if ( ! Auth::check()){
            return true;
        }

        $user = Auth::user();
        return $this->id !== $user->id;
    }

    public function getLogoUrlAttribute(){
        if ($this->logo){
            return asset('storage/uploads/images/logos/'.$this->logo);
        }
        return asset('assets/images/company.png');
    }

    public function payments(){
        return $this->hasMany(Payment::class);
    }
    public function getPremiumJobsBalanceAttribute($value){
        return $value;
    }

    public function checkJobBalace(){
        $totalPremiumJobsPaid = $this->payments()->success()->sum('premium_job');
        $totalPosted = $this->jobs()->whereIsPremium(1)->count();
        $balance = $totalPremiumJobsPaid - $totalPosted;

        $this->premium_jobs_balance = $balance;
        $this->save();
    }

    public function signed_up_datetime(){
        $created_date_time = $this->created_at->timezone(get_option('default_timezone'))->format(get_option('date_format_custom').' '.get_option('time_format_custom'));
        return $created_date_time;
    }
    public function status_context(){
        $status = $this->active_status;

        $context = '';
        switch ($status){
            case '0':
                $context = 'Pending';
                break;
            case '1':
                $context = 'Active';
                break;
            case '2':
                $context = 'Block';
                break;
        }
        return $context;
    }

}

codecanyon-23015013-jobfair-premium-laravel-php-job-board-script/jobfair/resources/views/blog-view.blade.php
@extends('layouts.theme')

@section('content')
    <div class="blog-single-page bg-white">
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="blog-single-title mt-5">
                        <h1>{{$post->title}}</h1>
                    </div>

                    <div class="blog-single-meta pt-3 mt-3">
                        <span><i class="la la-user"></i> {{$post->author->name}} </span>
                        <span><i class="la la-clock-o"></i> {{$post->created_at->diffForHumans()}} </span>
                        <span><i class="la la-eye"></i> {{$post->views}} </span>
                    </div>
                </div>
            </div>
        </div>

        @if($post->feature_image)
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="blog-single-title mt-5">

                            <img src="{{$post->feature_image_uri}}" title="{{$post->title}}" alt="{{$post->title}}" class="img-fluid" />

                        </div>
                    </div>
                </div>
            </div>
        @endif

        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="blog-single-content py-5">
                        {!! $post->post_content !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

codecanyon-23015013-jobfair-premium-laravel-php-job-board-script/jobfair/resources/views/checkout.blade.php
@extends('layouts.theme')

@section('content')
    <div class="checkout-page py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <h1>@lang('app.checkout')</h1>
                </div>
            </div>
        </div>
    </div>


    <div class="checkout-page bg-white py-5">

        @php
        $user= auth()->user();
        @endphp

        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="checkout-form pt-3 pb-5">

                        <form method="post">
                            @csrf

                        <p>{{$user->name}}</p>
                        <h4>Package: {{$package->package_name}}</h4>
                        <p>@lang('app.premium_job') : {{$package->premium_job}}</p>
                        <p class="text-success">@lang('app.price') : {!! get_amount($package->price) !!}</p>


                        <h4 class="my-5 text-muted">Choose your gateway</h4>

                        <div class="checkout-gateways-wrap">
                            <div class="checkout-gateway bg-light p-3 my-3">
                                <label>
                                    <input type="radio" name="gateway" value="paypal" checked="checked"> @lang('app.paypal')
                                </label>
                            </div>

                            <div class="checkout-gateway bg-light p-3 my-3">
                                <label>
                                    <input type="radio" name="gateway" value="stripe"> @lang('app.stripe')
                                </label>
                            </div>

                            <div class="checkout-gateway bg-light p-3 my-3">
                                <label>
                                    <input type="radio" name="gateway" value="bank_transfer"> @lang('app.bank_transfer')
                                </label>
                            </div>
                        </div>

                            <button class="btn btn-success btn-lg"><i class="la la-cart-arrow-down"></i> @lang('app.checkout')</button>


                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

codecanyon-23015013-jobfair-premium-laravel-php-job-board-script/jobfair/resources/views/jobs.blade.php
@extends('layouts.theme')

@section('content')


    <div class="blog-listing-header ">
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2 text-center">
                    <h1>@lang('app.search_jobs')</h1>
                    <h5>Filter from the left sidebar to find your desired job</h5>
                </div>
            </div>
        </div>
    </div>



    <div class="container">
        <div class="row">

            <div class="col-md-4">


                <div class="jobs-filter-form-wrap bg-white p-4 mt-4 mb-4">

                    <h4 class="mb-4">@lang('app.filter_jobs')</h4>

                    <form action="" method="get">

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.keywords')</p>
                            <input type="text" name="q" value="{{request('q')}}" class="form-control" style="min-width: 300px;" placeholder="@lang('app.job_title_placeholder')">
                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.gender')</p>

                            <select class="form-control" name="gender" id="gender">
                                <option value="">@lang('app.select_gender')</option>
                                <option value="any" {{ request('gender') == 'any' ? 'selected':'' }}>@lang('app.any')</option>
                                <option value="male" {{ request('gender') == 'male' ? 'selected':'' }}>@lang('app.male')</option>
                                <option value="female" {{ request('gender') == 'female' ? 'selected':'' }}>@lang('app.female')</option>
                                <option value="transgender" {{ request('gender') == 'transgender' ? 'selected':'' }}>@lang('app.transgender')</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.exp_level')</p>

                            <select class="form-control" name="exp_level" id="exp_level">
                                <option value="" >@lang('app.select_exp_level')</option>
                                <option value="mid" {{ request('exp_level') == 'mid' ? 'selected':'' }}>@lang('app.mid')</option>
                                <option value="entry" {{ request('exp_level') == 'entry' ? 'selected':'' }}>@lang('app.entry')</option>
                                <option value="senior" {{ request('exp_level') == 'senior' ? 'selected':'' }}>@lang('app.senior')</option>
                            </select>
                        </div>


                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.job_type')</p>

                            <select class="form-control" name="job_type" id="job_type">
                                <option value="">@lang('app.select_job_type')</option>
                                <option value="full_time" {{ request('job_type') == 'full_time' ? 'selected':'' }}>@lang('app.full_time')</option>
                                <option value="internship" {{ request('job_type') == 'internship' ? 'selected':'' }}>@lang('app.internship')</option>
                                <option value="part_time" {{ request('job_type') == 'part_time' ? 'selected':'' }}>@lang('app.part_time')</option>
                                <option value="contract" {{ request('job_type') == 'contract' ? 'selected':'' }}>@lang('app.contract')</option>
                                <option value="temporary" {{ request('job_type') == 'temporary' ? 'selected':'' }}>@lang('app.temporary')</option>
                                <option value="commission" {{ request('job_type') == 'commission' ? 'selected':'' }}>@lang('app.commission')</option>
                                <option value="internship" {{ request('job_type') == 'internship' ? 'selected':'' }}>@lang('app.internship')</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.category')</p>

                            <select class="form-control" name="category" id="category">
                                <option value="">@lang('app.select_category')</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}" {{selected($category->id, request('category'))}} >{{$category->category_name}}</option>
                                @endforeach
                            </select>

                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.country')</p>

                            <select name="country" class="form-control {{e_form_invalid_class('country', $errors)}} country_to_state">
                                <option value="">@lang('app.select_a_country')</option>
                                @foreach($countries as $country)
                                    <option value="{!! $country->id !!}" @if(request('country') && $country->id == request('country')) selected="selected" @endif  >{!! $country->country_name !!}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.state')</p>

                            <select name="state" class="form-control {{e_form_invalid_class('state', $errors)}} state_options">
                                <option value="">Select a state</option>

                                @if($old_country)
                                    @foreach($old_country->states as $state)
                                        <option value="{{$state->id}}" @if(request('state') && $state->id == request('state')) selected="selected" @endif >{!! $state->state_name !!}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>

                        <div class="form-group">
                            <p class="text-muted mb-1">@lang('app.location')</p>
                            <input type="text" name="location" value="{{request('location')}}" class="form-control" style="min-width: 300px;"  placeholder="@lang('app.job_location_placeholder')">
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success"><i class="la la-search"></i> @lang('app.filter_jobs')</button>
                            <a href="{{route('jobs_listing')}}" class="btn btn-info text-white"><i class="la la-eraser"></i> @lang('app.clear_filter')</a>
                        </div>
                    </form>

                </div>

            </div>

            <div class="col-md-8">

                <div class="employer-job-listing mt-4">

                    @if($jobs->count())

                        <div class="job-search-stats bg-white mb-3 p-4">
                            {!! sprintf(__('app.job_search_stats'), '<strong>', $jobs->total(), '</strong>') !!}
                        </div>

                        @foreach($jobs as $job)
                            <div class="employer-job-listing-single {{$job->is_premium? ' premium-job ' : '' }} box-shadow bg-white mb-3 p-3">

                                @if($job->is_premium)
                                    <div class="job-listing-company-logo">
                                        <a href="{{route('job_view', $job->job_slug)}}">
                                            <img src="{{$job->employer->logo_url}}" class="img-fluid" />
                                        </a>
                                    </div>
                                @endif

                                <div class="listing-job-info">

                                    <h5><a href="{{route('job_view', $job->job_slug)}}">{!! $job->job_title !!}</a> </h5>
                                    <p class="text-muted mb-1 mt-1">

                                        <i class="la la-clock-o"></i> @lang('app.posted') {{$job->created_at->diffForHumans()}}

                                        <i class="la la-calendar-times-o"></i> @lang('app.deadline') : {{$job->deadline->format(get_option('date_format'))}} <span class="text-small text-muted">{{$job->deadline->diffForHumans()}}</span>
                                    </p>

                                    @if($job->is_premium)
                                        <p class="text-muted mb-1 mt-1">
                                            <i class="la la-money"></i> {!! get_amount($job->salary, $job->salary_currency) !!} @if($job->salary_upto) - {!! get_amount($job->salary_upto, $job->salary_currency) !!} @endif / @lang('app.'.$job->salary_cycle),
                                            <i class="la la-th-list"></i> @lang('app.exp_level') : @lang('app.'.$job->exp_level)
                                        </p>




                                    @endif


                                    <p class="text-muted">
                                        <i class="la la-building-o"></i> {{$job->employer->company}}
                                        <i class="la la-briefcase"></i> @lang('app.'.$job->job_type)
                                        <i class="la la-map-marker"></i>
                                        @if($job->city_name)
                                            {!! $job->city_name !!},
                                        @endif
                                        @if($job->state_name)
                                            {!! $job->state_name !!},
                                        @endif
                                        @if($job->country_name)
                                            {!! $job->country_name !!}
                                        @endif
                                    </p>

                                </div>


                            </div>

                        @endforeach



                    @else


                        <div class="no-search-results-wrap text-center">

                            <p class="p-4">
                                <img src="{{asset('assets/images/no-search.png')}}" />
                            </p>

                            <h3>Whoops, no mathces</h3>
                            <h5 class="text-muted">We couldn't find any search results. </h5>
                            <h5 class="text-muted">Give it another try</h5>

                        </div>

                    @endif

                    {!! $jobs->links() !!}

                </div>

            </div>
        </div>
    </div>

@endsection

codecanyon-23015013-jobfair-premium-laravel-php-job-board-script/jobfair/resources/views/notice.blade.php
@extends('layouts.theme')

@section('content')
    <div class="checkout-page  bg-{{!empty($type)? $type : 'warning'}} py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <h1><i class="la la-warning"></i> @lang('app.notice')</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="checkout-page bg-white py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">


                    <h1 class="mb-4">{{$title}}</h1>
                    <h4 class="mb-4">{{$msg}}</h4>


                    <a href="" class="btn btn-outline-secondary btn-lg"> <i class="la la-home"></i> @lang('app.go_to_home')</a>

                </div>
            </div>
        </div>
    </div>
@endsection